### ISSUE TITLE
Disconnected CMs' ID stay in the area, and no one can get that certain ID anymore

### ISSUE THREAD

**Issue by KurokoShiroya** [AttorneyOnline/akashi#166]
Bug: If you CM in a area and DC, that ID that you had when you were cm'd will stay registered, and no one can get that ID anymore. How to reproduce: Go into a area, cm yourself, note your ID, and DC. When going back you would see that it will still say that ID is a CM and no one can grab that ID anymore because it's "taken"
Version: Master

**Comment by ApolloBrando** [comment]
To add to this, even if the person that has CM disconnects they still appear as being in the room in the area list and /getarea(s) commands.

They can be uncm'd and cm'd back and it will show their ID without a name on the area list.

**Comment by in1tiate** [comment]
Should be impossible.

```cpp
    bool l_updateLocks = false;

    for (AreaData* area : server->areas) {
        l_updateLocks = l_updateLocks || area->removeOwner(id);
    }

    if (l_updateLocks)
        arup(ARUPType::LOCKED, true);
    arup(ARUPType::CM, true);
```

This code runs whenever a client disconnects, and should remove disconnected clients from every area's owner list.

Additionally, the code for assigning new IDs:
```cpp
    for (AOClient* client : clients) {
        user_ids.append(client->id);
    }
    for (user_id = 0; user_id <= player_count; user_id++) {
        if (user_ids.contains(user_id))
            continue;
        else
            break;
    }
    AOClient* client = new AOClient(this, socket, this, user_id);
```

shouldn't even be taking area owners into account.

**Comment by in1tiate** [comment]
> 
> 
> To add to this, even if the person that has CM disconnects they still appear as being in the room in the area list and /getarea(s) commands.
> 
> They can be uncm'd and cm'd back and it will show their ID without a name on the area list.

Sounds like a ghost client problem. Would explain why the clientDisconnected() code isn't running.
