### ISSUE TITLE
Sometimes different people are assigned the same ID

### ISSUE THREAD

**Issue by ApolloBrando** [AttorneyOnline/akashi#169]
From what i've seen sometimes people that join roughly at the same time are given the same ID.

**Comment by KurokoShiroya** [comment]
In addition, I know this is obvious but whatever happens to one of them, it happens to the other. For example, there are 2 ID 43s, one gets CM'd, the other will too. Same goes for /area_kick and etc.

**Comment by in1tiate** [comment]
should be impossible

**Comment by in1tiate** [comment]
possible fix: randomly select the new id from a pool ranging from zero to the max player count instead of assigning the first available value from that pool

this is not so much a fix as it is mitigation to drastically decrease the likelihood of collisions

**Comment by Salanto** [comment]
Considered fixed due to merge of #221.
