### ISSUE TITLE
Pairing maintains the partner's sprite when switching areas.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#232]
A user went into a private area with a friend, paired in said area, and then returned to the main area to chat, and their partner's sprite (Kyoko) still showed on screen despite them not being in the area.

![image](https://user-images.githubusercontent.com/30537683/156942472-d4f5e030-c034-4efa-b0b5-a0a0173e40eb.png)
![image](https://user-images.githubusercontent.com/30537683/156942488-828ef1e2-683d-4a12-a0af-08515c392e6e.png)

**Comment by AwesomeAim** [comment]
Just reproducing this error since it kinda lacks that and was just reported off of others demonstrating it.

Took two clients into a private area, paired with each other, went back into the main area, and talked, and the pair was maintained.

![image](https://user-images.githubusercontent.com/30537683/159206350-39c0dc8d-f274-4391-9e9e-3f0a92493abf.png)
(left is in a private area, right is in main hall)

![image](https://user-images.githubusercontent.com/30537683/159206435-4847326e-1b9d-443a-8dd6-a3ff9986e910.png)
(upon closing Yukari's client, the cross-area pair stops)

**Comment by Salanto** [comment]
resolved by #269
