### ISSUE TITLE
[Bug/Regression] Upon stopping the music by attempting to play the category, it should show "User has stopped the music."

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#234]
Currently, it displays "User has played a song: ." which looks odd. 
![image](https://user-images.githubusercontent.com/30537683/157151071-98433068-bffd-4ee0-8789-0573b8a1499a.png)

**Comment by in1tiate** [comment]
The reason this happens is that playing a category is not the intended way to stop the music - the intended way is to right click the music list and click "Stop". This should probably be fixed anyway but that's why it happens

**Comment by AwesomeAim** [comment]
That's reasonable, though I don't see a way for web to do that. And uh, even when I do it like that, it still displays the same: 
![image](https://user-images.githubusercontent.com/30537683/157553903-0759d14d-1b60-4356-8e57-f6c9e917bc7f.png)
![image](https://user-images.githubusercontent.com/30537683/157553935-654f6bb8-02e2-422c-82da-63a7ef4cf2ff.png)
![image](https://user-images.githubusercontent.com/30537683/157553948-525cc5f3-1511-42cb-a5e7-f93ce2597637.png)
That's on 2.9.1 though, so maybe it's already been changed for 2.10.

**Comment by in1tiate** [comment]
oh then thats just a regression, oops
