### ISSUE TITLE
[Feature Request] A command that removes all multiclients except the one that ran it.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#239]
When a user disconnects via their internet crashing, it never has a chance to tell the server that they aren't there any more. As a result, it leaves a ghost client until it times out, and the user is forced to reconnect but not be able to choose their character. The command would allow a user to disconnect said ghost clients without having to ask an admin to kick them. KFO-Server has this command but it's called /kms which is, a bit of a crude name.

**Comment by Salanto** [comment]
The infamous CaseCafe /kickother
