### ISSUE TITLE
On the wiki, /getbaninfo is referenced, but the command is actually /baninfo.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#249]
https://github.com/AttorneyOnline/akashi/wiki/Moderation#getbaninfo

I don't know how to/can't edit wikis so I can't just fix that myself. I think the command syntax listed may be wrong too? The /help baninfo only returns this

![image](https://user-images.githubusercontent.com/30537683/159183812-6f2d7f91-5db5-4629-b619-bf11d0d948d0.png)

**Comment by in1tiate** [comment]
Fixed, thank you!
