### ISSUE TITLE
If web attempts to use a judge bench, client cannot see it.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#254]
Left is webtest view, right is client view.
![image](https://user-images.githubusercontent.com/30537683/161405477-74659ea8-ef72-4435-b3f3-f4bcb897d4af.png)
^ user talking is on webtest
![image](https://user-images.githubusercontent.com/30537683/161405483-41d06d8e-76a9-4df3-91f4-3d5f807d52d4.png)
^ user talking is on client (me)

It's specifically a server issue as the behaviour changes on other servers. Client 2.9 or using a different web don't change it. KFO-Server has this fixed, while something like TsuOLE has it broken regardless of who uses the judge bench.

**Comment by Salanto** [comment]
wtf
