### ISSUE TITLE
Spectators can play music

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#257]
Whether spectators shouldn't be allowed to change the music, or it should be displaying it properly that they did, either way there's an issue here. Presumably it breaks trying to find the character name/showname of the spectator as they have none and displays nothing as a result, but it still does change the music, which looks quite odd.

**Comment by in1tiate** [comment]
The problem is spectators being allowed to change music, the music system uses CID -1 for silent track changes

**Comment by Salanto** [comment]
We should probably tie more information to an internal variable opposed to checking the character ID to decouple those two a bit more.
