### ISSUE TITLE
The Wiki mentions /flip, but the command is actually /coinflip

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#260]
https://github.com/AttorneyOnline/akashi/wiki/Roleplay

![image](https://user-images.githubusercontent.com/30537683/167299671-0073402e-d712-4a03-adaf-601deadf8a41.png)

**Comment by AwesomeAim** [comment]
oh while I'm here with this, there's a typo here: https://github.com/AttorneyOnline/akashi/wiki/Areas

![image](https://user-images.githubusercontent.com/30537683/167300194-c299e10e-516e-4198-a09f-fd8dd09f2f19.png)

wether should be whether

**Comment by stonedDiscord** [comment]
done
