### ISSUE TITLE
The command /ignorebglist is completely missing on the wiki

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#265]
![image](https://user-images.githubusercontent.com/30537683/170356539-31be96c6-92da-4c98-b200-e1fdf1c75b26.png)
I found this on a complete and utter fluke checking to see if there was a way to do this exact thing, since I recall the permission IGNORE_BGLIST existing as mentioned. It works as intended and has no issues, but is merely undocumented on the wiki.
![image](https://user-images.githubusercontent.com/30537683/170358439-6b825edd-5cd4-4f8d-b9bd-075a6dd0c2fa.png)

**Comment by Salanto** [comment]
Added
