### ISSUE TITLE
The Adding Areas documentation is missing ignore_bglist and jukebox_enabled

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#266]
https://github.com/AttorneyOnline/akashi/wiki/Adding-Areas
The other half of things I found on my bg list escapade. As referenced in area_data.cpp
![image](https://user-images.githubusercontent.com/30537683/170361414-3b8654ea-cea5-41cc-a8d0-5082015e77e0.png)

**Comment by Salanto** [comment]
Added to the wiki
