### ISSUE TITLE
kick_other does not account for IPv6

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/akashi#275]
Fml
Since Akashi supports both IPv4 and IPv6 there is a chance that a client reconnecting results in communication over the other protocol, causing kick_other to be unable to identify the other client for kicking.

Solution : 
Allow users to either kick_other by HDID or IPID. This would limit kick_other to either the same IP or the same HWID. A bit janky, but so is the concept of the command itself if we are being honest here.

**Comment by in1tiate** [comment]
wow this is an annoying bug

**Comment by Salanto** [comment]
Unfixable too unless I start using some black magic to build a character relation sheet with HDID and IPID statistic analysis which would be very error-prone to determine who is who..
