### ISSUE TITLE
Rarely, again, a character will become permanently unpickable in an area.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/akashi#307]
/getarea
![image](https://user-images.githubusercontent.com/30537683/177038547-9ce3e0d2-20fe-481b-b9e4-acd1e51d9ca6.png)
Character selection list:
![image](https://user-images.githubusercontent.com/30537683/177038607-7c9d3e0e-1996-45e5-a776-5a22e6697889.png)
![image](https://user-images.githubusercontent.com/30537683/177038572-96ccb3d4-7fa5-4d96-989b-8de9d296fe89.png)
Margaret is considered "picked" despite the fact that there is no such Margaret in the area.

**Comment by in1tiate** [comment]
this will need reproduction before it can be addressed

**Comment by AwesomeAim** [comment]
Steps to reproduce (there could be multiple routes but this works for me):

1. Connect to akashi via webao
2. Before everything loads, select a character (aka, immediately select a character)
3. Immediately alt+f4
4. Character becomes permanently locked

**Comment by Salanto** [comment]
Resolved by #321
