### ISSUE TITLE
Modcall OOC messages are missing a trailing newline

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/akashi#384]
re @stonedDiscord: 
![image](https://github.com/user-attachments/assets/61bd3c89-2466-41ac-82df-a021bed0b813)

**Comment by stonedDiscord** [comment]
this seems to be a web only issue as the newlines do appear in
https://github.com/AttorneyOnline/akashi/blob/master/src/packet/packet_zz.cpp#L30
and there is no CT packet being sent
