### ISSUE TITLE
Text Box being weird.

### ISSUE THREAD

**Issue by Kitsu-76** [AttorneyOnline/akashi#49]
1. chat arrow appears sometimes, never on the default textbox. 2. text gets misplaced on default textbox. 3. Default character name not shown even if there was a showname typed in. We think it may have to do with the showname being blank if nothing is typed in to the IC chat name. These may be clientside, but I highly doubt it. Definitely need to check them.

**Comment by in1tiate** [comment]
The first two problems you have are client-side. Please file an issue on the AO2-Client repository: https://github.com/AttorneyOnline/AO2-Client

Additionally, please make separate issues when you have multiple problems. Closing as invalid.
